/**
 * Sleeper API
 * The Sleeper API is a read-only HTTP API that is free to use and allows             access to a users leagues, drafts, and rosters. No API Token is necessary, as you cannot modify contents via this API. Be mindful of the frequency of calls. A general rule is to stay under 1000 API calls per minute, otherwise, you risk being IP-blocked.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* picks that were traded
*/
export class DraftPick {
    /**
    * the season this draft pick belongs to
    */
    'season': string;
    /**
    * which round this draft pick is
    */
    'round': number;
    /**
    * original owner's roster_id
    */
    'rosterId': number;
    /**
    * previous owner's roster id (in this trade)
    */
    'previousOwnerId': number;
    /**
    * the new owner of this pick after the trade
    */
    'ownerId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "season",
            "baseName": "season",
            "type": "string",
            "format": ""
        },
        {
            "name": "round",
            "baseName": "round",
            "type": "number",
            "format": ""
        },
        {
            "name": "rosterId",
            "baseName": "roster_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "previousOwnerId",
            "baseName": "previous_owner_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "ownerId",
            "baseName": "owner_id",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DraftPick.attributeTypeMap;
    }
    
    public constructor() {
    }
}

