/**
 * Sleeper API
 * The Sleeper API is a read-only HTTP API that is free to use and allows             access to a users leagues, drafts, and rosters. No API Token is necessary, as you cannot modify contents via this API. Be mindful of the frequency of calls. A general rule is to stay under 1000 API calls per minute, otherwise, you risk being IP-blocked.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DraftSettings {
    'teams': number;
    'slotsWr': number;
    'slotsTe': number;
    'slotsRb': number;
    'slotsQb': number;
    'slotsK': number;
    'slotsFlex': number;
    'slotsDef': number;
    'slotsBn': number;
    'rounds': number;
    'pickTimer': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "teams",
            "baseName": "teams",
            "type": "number",
            "format": ""
        },
        {
            "name": "slotsWr",
            "baseName": "slots_wr",
            "type": "number",
            "format": ""
        },
        {
            "name": "slotsTe",
            "baseName": "slots_te",
            "type": "number",
            "format": ""
        },
        {
            "name": "slotsRb",
            "baseName": "slots_rb",
            "type": "number",
            "format": ""
        },
        {
            "name": "slotsQb",
            "baseName": "slots_qb",
            "type": "number",
            "format": ""
        },
        {
            "name": "slotsK",
            "baseName": "slots_k",
            "type": "number",
            "format": ""
        },
        {
            "name": "slotsFlex",
            "baseName": "slots_flex",
            "type": "number",
            "format": ""
        },
        {
            "name": "slotsDef",
            "baseName": "slots_def",
            "type": "number",
            "format": ""
        },
        {
            "name": "slotsBn",
            "baseName": "slots_bn",
            "type": "number",
            "format": ""
        },
        {
            "name": "rounds",
            "baseName": "rounds",
            "type": "number",
            "format": ""
        },
        {
            "name": "pickTimer",
            "baseName": "pick_timer",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DraftSettings.attributeTypeMap;
    }
    
    public constructor() {
    }
}

