/**
 * Sleeper API
 * The Sleeper API is a read-only HTTP API that is free to use and allows             access to a users leagues, drafts, and rosters. No API Token is necessary, as you cannot modify contents via this API. Be mindful of the frequency of calls. A general rule is to stay under 1000 API calls per minute, otherwise, you risk being IP-blocked.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LeagueSettings {
    'maxKeepers': number;
    'draftRounds': number;
    'tradeReviewDays': number;
    'reserveAllowDnr': number;
    'capacityOverride': number;
    'pickTrading': number;
    'taxiYears': number;
    'taxiAllowVets': number;
    'disableAdds': number;
    'waiverType': number;
    'benchLock': number;
    'reserveAllowSus': number;
    'type': number;
    'reserveAllowCov': number;
    'waiverClearDays': number;
    'waiverDayOfWeek': number;
    'playoffTeams': number;
    'numTeams': number;
    'reserveSlots': number;
    'playoffRoundType': number;
    'dailyWaiversHour': number;
    'waiverBudget': number;
    'reserveAllowOut': number;
    'offseasonAdds': number;
    'playoffSeedType': number;
    'dailyWaivers': number;
    'playoffWeekStart': number;
    'leagueAverageMatch': number;
    'leg': number;
    'tradeDeadline': number;
    'reserveAllowDoubtful': number;
    'taxiDeadline': number;
    'reserveAllowNa': number;
    'taxiSlots': number;
    'playoffType': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "maxKeepers",
            "baseName": "max_keepers",
            "type": "number",
            "format": ""
        },
        {
            "name": "draftRounds",
            "baseName": "draft_rounds",
            "type": "number",
            "format": ""
        },
        {
            "name": "tradeReviewDays",
            "baseName": "trade_review_days",
            "type": "number",
            "format": ""
        },
        {
            "name": "reserveAllowDnr",
            "baseName": "reserve_allow_dnr",
            "type": "number",
            "format": ""
        },
        {
            "name": "capacityOverride",
            "baseName": "capacity_override",
            "type": "number",
            "format": ""
        },
        {
            "name": "pickTrading",
            "baseName": "pick_trading",
            "type": "number",
            "format": ""
        },
        {
            "name": "taxiYears",
            "baseName": "taxi_years",
            "type": "number",
            "format": ""
        },
        {
            "name": "taxiAllowVets",
            "baseName": "taxi_allow_vets",
            "type": "number",
            "format": ""
        },
        {
            "name": "disableAdds",
            "baseName": "disable_adds",
            "type": "number",
            "format": ""
        },
        {
            "name": "waiverType",
            "baseName": "waiver_type",
            "type": "number",
            "format": ""
        },
        {
            "name": "benchLock",
            "baseName": "bench_lock",
            "type": "number",
            "format": ""
        },
        {
            "name": "reserveAllowSus",
            "baseName": "reserve_allow_sus",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number",
            "format": ""
        },
        {
            "name": "reserveAllowCov",
            "baseName": "reserve_allow_cov",
            "type": "number",
            "format": ""
        },
        {
            "name": "waiverClearDays",
            "baseName": "waiver_clear_days",
            "type": "number",
            "format": ""
        },
        {
            "name": "waiverDayOfWeek",
            "baseName": "waiver_day_of_week",
            "type": "number",
            "format": ""
        },
        {
            "name": "playoffTeams",
            "baseName": "playoff_teams",
            "type": "number",
            "format": ""
        },
        {
            "name": "numTeams",
            "baseName": "num_teams",
            "type": "number",
            "format": ""
        },
        {
            "name": "reserveSlots",
            "baseName": "reserve_slots",
            "type": "number",
            "format": ""
        },
        {
            "name": "playoffRoundType",
            "baseName": "playoff_round_type",
            "type": "number",
            "format": ""
        },
        {
            "name": "dailyWaiversHour",
            "baseName": "daily_waivers_hour",
            "type": "number",
            "format": ""
        },
        {
            "name": "waiverBudget",
            "baseName": "waiver_budget",
            "type": "number",
            "format": ""
        },
        {
            "name": "reserveAllowOut",
            "baseName": "reserve_allow_out",
            "type": "number",
            "format": ""
        },
        {
            "name": "offseasonAdds",
            "baseName": "offseason_adds",
            "type": "number",
            "format": ""
        },
        {
            "name": "playoffSeedType",
            "baseName": "playoff_seed_type",
            "type": "number",
            "format": ""
        },
        {
            "name": "dailyWaivers",
            "baseName": "daily_waivers",
            "type": "number",
            "format": ""
        },
        {
            "name": "playoffWeekStart",
            "baseName": "playoff_week_start",
            "type": "number",
            "format": ""
        },
        {
            "name": "leagueAverageMatch",
            "baseName": "league_average_match",
            "type": "number",
            "format": ""
        },
        {
            "name": "leg",
            "baseName": "leg",
            "type": "number",
            "format": ""
        },
        {
            "name": "tradeDeadline",
            "baseName": "trade_deadline",
            "type": "number",
            "format": ""
        },
        {
            "name": "reserveAllowDoubtful",
            "baseName": "reserve_allow_doubtful",
            "type": "number",
            "format": ""
        },
        {
            "name": "taxiDeadline",
            "baseName": "taxi_deadline",
            "type": "number",
            "format": ""
        },
        {
            "name": "reserveAllowNa",
            "baseName": "reserve_allow_na",
            "type": "number",
            "format": ""
        },
        {
            "name": "taxiSlots",
            "baseName": "taxi_slots",
            "type": "number",
            "format": ""
        },
        {
            "name": "playoffType",
            "baseName": "playoff_type",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LeagueSettings.attributeTypeMap;
    }
    
    public constructor() {
    }
}

