/**
 * Sleeper API
 * The Sleeper API is a read-only HTTP API that is free to use and allows             access to a users leagues, drafts, and rosters. No API Token is necessary, as you cannot modify contents via this API. Be mindful of the frequency of calls. A general rule is to stay under 1000 API calls per minute, otherwise, you risk being IP-blocked.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SportState {
    /**
    * week
    */
    'week': number;
    /**
    * pre, post, regular
    */
    'seasonType': SportStateSeasonTypeEnum;
    /**
    * regular season start
    */
    'seasonStartDate': string;
    /**
    * current season
    */
    'season': string;
    /**
    * previous season
    */
    'previousSeason': string;
    /**
    * week of regular season
    */
    'leg': number;
    /**
    * active season for leagues
    */
    'leagueSeason': string;
    /**
    * flips in December
    */
    'leagueCreateSeason': string;
    /**
    * Which week to display in UI, can be different than week
    */
    'displayWeek': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "week",
            "baseName": "week",
            "type": "number",
            "format": ""
        },
        {
            "name": "seasonType",
            "baseName": "season_type",
            "type": "SportStateSeasonTypeEnum",
            "format": ""
        },
        {
            "name": "seasonStartDate",
            "baseName": "season_start_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "season",
            "baseName": "season",
            "type": "string",
            "format": ""
        },
        {
            "name": "previousSeason",
            "baseName": "previous_season",
            "type": "string",
            "format": ""
        },
        {
            "name": "leg",
            "baseName": "leg",
            "type": "number",
            "format": ""
        },
        {
            "name": "leagueSeason",
            "baseName": "league_season",
            "type": "string",
            "format": ""
        },
        {
            "name": "leagueCreateSeason",
            "baseName": "league_create_season",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayWeek",
            "baseName": "display_week",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SportState.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type SportStateSeasonTypeEnum = "pre" | "post" | "regular" ;

